import { BikeData } from './types';

const bikes: BikeData[] = [
  {
    num: 1,
    photo: './assets/images/ktm-prowler.webp',
    manufacturer: 'KTM',
    name: 'KTM Prowler Master',
    year: 2020,
    wheels: 29,
    frame: 'L',
    category: 'Горный',
    color: 'серый',
    stock: 10,
    buy: true,
    popular: true,
  },
  {
    num: 2,
    photo: './assets/images/ktm-x-strada.webp',
    manufacturer: 'KTM',
    name: 'KTM X-Strada Prime',
    year: 2022,
    wheels: 28,
    frame: 'M',
    category: 'Гравийный',
    color: 'белый',
    stock: 5,
    buy: false,
    popular: false,
  },
  {
    num: 3,
    photo: './assets/images/ktm-city-fun.webp',
    manufacturer: 'KTM',
    name: 'KTM City Fun 28',
    year: 2021,
    wheels: 28,
    frame: 'L',
    category: 'Городской',
    color: 'белый',
    stock: 25,
    buy: false,
    popular: true,
  },
  {
    num: 4,
    photo: './assets/images/ktm-revelator-alto.webp',
    manufacturer: 'KTM',
    name: 'KTM Revelator Alto Master',
    year: 2022,
    wheels: 28,
    frame: 'XL',
    category: 'Шоссейный',
    color: 'красный',
    stock: 2,
    buy: false,
    popular: false,
  },
  {
    num: 5,
    photo: './assets/images/merida-big-nine.webp',
    manufacturer: 'Merida',
    name: 'Merida Big.Nine 9000',
    year: 2022,
    wheels: 27.5,
    frame: 'M',
    category: 'Горный',
    color: 'черный',
    stock: 12,
    buy: false,
    popular: true,
  },
  {
    num: 6,
    photo: './assets/images/merida-silex.webp',
    manufacturer: 'Merida',
    name: 'Merida Silex 200',
    year: 2019,
    wheels: 28,
    frame: 'L',
    category: 'Гравийный',
    color: 'серый',
    stock: 1,
    buy: false,
    popular: false,
  },
  {
    num: 7,
    photo: './assets/images/merida-scultura.webp',
    manufacturer: 'Merida',
    name: 'Merida Scultura Disc 400',
    year: 2019,
    wheels: 28,
    frame: 'M',
    category: 'Шоссейный',
    color: 'синий',
    stock: 3,
    buy: false,
    popular: false,
  },
  {
    num: 8,
    photo: './assets/images/merida-speeder.webp',
    manufacturer: 'Merida',
    name: 'Merida Speeder 10-V (L)',
    year: 2022,
    wheels: 28,
    frame: 'S',
    category: 'Городской',
    color: 'серый',
    stock: 13,
    buy: false,
    popular: true,
  },
  {
    num: 9,
    photo: './assets/images/giant-cypress.webp',
    manufacturer: 'Giant',
    name: 'Giant Cypress 1',
    year: 2021,
    wheels: 28,
    frame: 'M',
    category: 'Городской',
    color: 'синий',
    stock: 7,
    buy: true,
    popular: true,
  },
  {
    num: 10,
    photo: './assets/images/giant-stp.webp',
    manufacturer: 'Giant',
    name: 'Giant STP 26',
    year: 2020,
    wheels: 26,
    frame: 'L',
    category: 'Горный',
    color: 'серый',
    stock: 15,
    buy: false,
    popular: true,
  },
  {
    num: 11,
    photo: './assets/images/giant-revolt.webp',
    manufacturer: 'Giant',
    name: 'Giant Revolt 0',
    year: 2022,
    wheels: 29,
    frame: 'XL',
    category: 'Гравийный',
    color: 'белый',
    stock: 7,
    buy: false,
    popular: false,
  },
  {
    num: 12,
    photo: './assets/images/giant-tcr-advanced.webp',
    manufacturer: 'Giant',
    name: 'Giant TCR Advanced 3',
    year: 2020,
    wheels: 28,
    frame: 'M',
    category: 'Шоссейный',
    color: 'белый',
    stock: 1,
    buy: false,
    popular: false,
  },
  {
    num: 13,
    photo: './assets/images/fuji-traverse.webp',
    manufacturer: 'FUJI',
    name: 'FUJI Traverse 1.3',
    year: 2018,
    wheels: 27.5,
    frame: 'M',
    category: 'Горный',
    color: 'оранжевый',
    stock: 1,
    buy: false,
    popular: false,
  },
  {
    num: 14,
    photo: './assets/images/fuji-absolute.webp',
    manufacturer: 'FUJI',
    name: 'FUJI Absolute 1.9',
    year: 2020,
    wheels: 28,
    frame: 'M',
    category: 'Городской',
    color: 'синий',
    stock: 11,
    buy: false,
    popular: true,
  },
  {
    num: 15,
    photo: './assets/images/fuji-sl-a.webp',
    manufacturer: 'FUJI',
    name: 'FUJI SL-A 1.3',
    year: 2022,
    wheels: 28,
    frame: 'XL',
    category: 'Шоссейный',
    color: 'синий',
    stock: 1,
    buy: false,
    popular: false,
  },
  {
    num: 16,
    photo: './assets/images/aist-mach.webp',
    manufacturer: 'AIST',
    name: 'AIST Mach 1.0',
    year: 2017,
    wheels: 28,
    frame: 'L',
    category: 'Шоссейный',
    color: 'серый',
    stock: 13,
    buy: false,
    popular: true,
  },
  {
    num: 17,
    photo: './assets/images/aist-slide.webp',
    manufacturer: 'AIST',
    name: 'AIST Slide 3.0',
    year: 2017,
    wheels: 27.5,
    frame: 'S',
    category: 'Горный',
    color: 'черный',
    stock: 10,
    buy: true,
    popular: true,
  },
  {
    num: 18,
    photo: './assets/images/aist-tracker.webp',
    manufacturer: 'AIST',
    name: 'AIST Tracker 2.0',
    year: 2018,
    wheels: 26,
    frame: 'S',
    category: 'Городской',
    color: 'оранжевый',
    stock: 20,
    buy: false,
    popular: true,
  },
  {
    num: 19,
    photo: './assets/images/aist-cross.webp',
    manufacturer: 'AIST',
    name: 'AIST Cross 2.0',
    year: 2019,
    wheels: 28,
    frame: 'L',
    category: 'Городской',
    color: 'серый',
    stock: 5,
    buy: false,
    popular: false,
  },
  {
    num: 20,
    photo: './assets/images/format-1411.webp',
    manufacturer: 'Format',
    name: 'Format 1411 27,5',
    year: 2021,
    wheels: 27.5,
    frame: 'M',
    category: 'Горный',
    color: 'серый',
    stock: 12,
    buy: false,
    popular: true,
  },
  {
    num: 21,
    photo: './assets/images/format-2221.webp',
    manufacturer: 'Format',
    name: 'Format 2221',
    year: 2022,
    wheels: 28,
    frame: 'XL',
    category: 'Шоссейный',
    color: 'красный',
    stock: 2,
    buy: false,
    popular: false,
  },
  {
    num: 22,
    photo: './assets/images/format-5211.webp',
    manufacturer: 'Format',
    name: 'Format 5211',
    year: 2022,
    wheels: 28,
    frame: 'L',
    category: 'Гравийный',
    color: 'серый',
    stock: 3,
    buy: false,
    popular: false,
  },
  {
    num: 23,
    photo: './assets/images/format-5522.webp',
    manufacturer: 'Format',
    name: 'Format 5522',
    year: 2022,
    wheels: 26,
    frame: 'S',
    category: 'Городской',
    color: 'красный',
    stock: 13,
    buy: false,
    popular: true,
  },
];

export default bikes;
