import { BikeDataArray } from "./types";

export const bikes: BikeDataArray = [
  {
    "photo": "./assets/images/ktm-prowler.jpg",
    "manufacturer": "KTM",
    "name": "KTM Prowler Master",
    "year": 2020,
    "wheels": 29,
    "size": "L",
    "category": "Mountain",
    "color": "Grey",
    "stock": 10,
    "buy": true,
    "popular": true
  },
  {
    "photo": "./assets/images/ktm-x-strada.jpg",
    "manufacturer": "KTM",
    "name": "KTM X-Strada Prime",
    "year": 2022,
    "wheels": 28,
    "size": "M",
    "category": "Gravel",
    "color": "White",
    "stock": 5,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/ktm-city-fun.jpg",
    "manufacturer": "KTM",
    "name": "KTM City Fun 28",
    "year": 2021,
    "wheels": 28,
    "size": "L",
    "category": "City",
    "color": "White",
    "stock": 25,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/ktm-revelator-alto.jpg",
    "manufacturer": "KTM",
    "name": "KTM Revelator Alto Master",
    "year": 2022,
    "wheels": 28,
    "size": "XL",
    "category": "Road",
    "color": "Red",
    "stock": 2,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/merida-big-nine.jpg",
    "manufacturer": "Merida",
    "name": "Merida Big.Nine 9000",
    "year": 2022,
    "wheels": 27.5,
    "size": "M",
    "category": "Mountain",
    "color": "Black",
    "stock": 12,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/merida-silex.jpg",
    "manufacturer": "Merida",
    "name": "Merida Silex 200",
    "year": 2019,
    "wheels": 28,
    "size": "L",
    "category": "Gravel",
    "color": "Grey",
    "stock": 1,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/merida-scultura.jpg",
    "manufacturer": "Merida",
    "name": "Merida Scultura Disc 400",
    "year": 2019,
    "wheels": 28,
    "size": "M",
    "category": "Road",
    "color": "Blue",
    "stock": 3,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/merida-speeder.jpg",
    "manufacturer": "Merida",
    "name": "Merida Speeder 10-V (L)",
    "year": 2022,
    "wheels": 28,
    "size": "S",
    "category": "City",
    "color": "Grey",
    "stock": 13,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/giant-cypress.jpg",
    "manufacturer": "Giant",
    "name": "Giant Cypress 1",
    "year": 2021,
    "wheels": 28,
    "size": "M",
    "category": "City",
    "color": "Blue",
    "stock": 7,
    "buy": true,
    "popular": true
  },
  {
    "photo": "./assets/images/giant-stp.jpg",
    "manufacturer": "Giant",
    "name": "Giant STP 26",
    "year": 2020,
    "wheels": 26,
    "size": "L",
    "category": "Mountain",
    "color": "Grey",
    "stock": 15,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/giant-revolt.jpg",
    "manufacturer": "Giant",
    "name": "Giant Revolt 0",
    "year": 2022,
    "wheels": 29,
    "size": "XL",
    "category": "Gravel",
    "color": "White",
    "stock": 7,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/giant-tcr-advanced.jpg",
    "manufacturer": "Giant",
    "name": "Giant TCR Advanced 3",
    "year": 2020,
    "wheels": 28,
    "size": "M",
    "category": "Road",
    "color": "White",
    "stock": 1,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/fuji-traverse.jpg",
    "manufacturer": "FUJI",
    "name": "FUJI Traverse 1.3",
    "year": 2018,
    "wheels": 27.5,
    "size": "M",
    "category": "Mountain",
    "color": "Orange",
    "stock": 1,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/fuji-absolute.jpg",
    "manufacturer": "FUJI",
    "name": "FUJI Absolute 1.9",
    "year": 2020,
    "wheels": 28,
    "size": "M",
    "category": "City",
    "color": "Blue",
    "stock": 11,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/fuji-sl-a.jpg",
    "manufacturer": "FUJI",
    "name": "FUJI SL-A 1.3",
    "year": 2022,
    "wheels": 28,
    "size": "XL",
    "category": "Road",
    "color": "Blue",
    "stock": 1,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/aist-mach.jpg",
    "manufacturer": "AIST",
    "name": "AIST Mach 1.0",
    "year": 2017,
    "wheels": 28,
    "size": "L",
    "category": "Road",
    "color": "Grey",
    "stock": 13,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/aist-slide.jpg",
    "manufacturer": "AIST",
    "name": "AIST Slide 3.0",
    "year": 2017,
    "wheels": 27.5,
    "size": "S",
    "category": "Mountain",
    "color": "Black",
    "stock": 10,
    "buy": true,
    "popular": true
  },
  {
    "photo": "./assets/images/aist-tracker.jpg",
    "manufacturer": "AIST",
    "name": "AIST Tracker 2.0",
    "year": 2018,
    "wheels": 26,
    "size": "S",
    "category": "City",
    "color": "Orange",
    "stock": 20,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/aist-cross.jpg",
    "manufacturer": "AIST",
    "name": "AIST Cross 2.0",
    "year": 2019,
    "wheels": 28,
    "size": "L",
    "category": "City",
    "color": "Grey",
    "stock": 5,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/format-1411.jpg",
    "manufacturer": "Format",
    "name": "Format 1411 27,5",
    "year": 2021,
    "wheels": 27.5,
    "size": "M",
    "category": "Mountain",
    "color": "Grey",
    "stock": 12,
    "buy": false,
    "popular": true
  },
  {
    "photo": "./assets/images/format-2221.jpg",
    "manufacturer": "Format",
    "name": "Format 2221",
    "year": 2022,
    "wheels": 28,
    "size": "XL",
    "category": "Road",
    "color": "Red",
    "stock": 2,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/format-5211.jpg",
    "manufacturer": "Format",
    "name": "Format 5211",
    "year": 2022,
    "wheels": 28,
    "size": "L",
    "category": "Gravel",
    "color": "Grey",
    "stock": 3,
    "buy": false,
    "popular": false
  },
  {
    "photo": "./assets/images/format-5522.jpg",
    "manufacturer": "Format",
    "name": "Format 5522",
    "year": 2022,
    "wheels": 26,
    "size": "S",
    "category": "City",
    "color": "Red",
    "stock": 13,
    "buy": false,
    "popular": true
  }
]